### ISSUE TITLE
folder

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_scratches#1]
data/scratches is much better - user will not loose files on pluigin reinstall. and now Cud installs plugin by removing its folder first.

**Comment by Alexey-T** [comment]
![dd](https://user-images.githubusercontent.com/4154978/152612365-ce188a7d-dcbd-4c35-b76a-119b978b55aa.png)

**Comment by ildarkhasanshin** [comment]
> why not 'date/scracthes'

так и в продуктах от jetbrains
так-то дата файла и первые пять строк отображают в списке всех scracthes

**Comment by ildarkhasanshin** [comment]
> user will not loose files on pluigin reinstall

ок, переделаю

**Comment by ildarkhasanshin** [comment]
> ок, переделаю

done
