### ISSUE TITLE
item.replace(PATH+os.sep, '', 1)

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_scratches#10]
you need here the only-filename-path?
then use this

    os.path.basename(item)

it is proper way. replace() is bad here.

I see 2 places for replace()

**Comment by Alexey-T** [comment]
2 places:
seems good is this:

1.

        items_ = items_ + os.path.basename(item) + ' | ' + dt.fromtimestamp(getctime(item)).strftime('%Y-%m-%d %H:%M:%S') + ' | ' + convert_size(os.path.getsize(item)) + "\t" + preview + "\n"


2.

            msg_box('Removed scratch: '+os.path.basename(items[res]), MB_OK)

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/03593496eb415fc306d5f2d7140802b84fa97a69
