### ISSUE TITLE
dont show dlg_menu dlgs when no snippets yet

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_scratches#13]
show only msg_status('No scratches found')

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/5aa0969f83eef5f5847782e15cf5a66d6b683f4d

**Comment by Alexey-T** [comment]
for 'delete' and for 'list'

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/87902981ec47179c94870e7ce090481125768196

**Comment by Alexey-T** [comment]
ok
