### ISSUE TITLE
if bool_value == True

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_scratches#16]
no need to compare with True or False.
ujse this

if bool_var

or 

if not bool_var

**Comment by Alexey-T** [comment]
if (os.path.exists(PATH) == False):

and

        while (os.path.exists(fname) == True):

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/e75874ba5cdd8f2bb5994c0b0ab59454280aadf9
