### ISSUE TITLE
plugin name is not full in the Addon Manager dlg, see install.inf

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_scratches#2]
e.g. command "Edit plugin" shows this weird name

![Screenshot from 2022-02-05 01-36-37](https://user-images.githubusercontent.com/4154978/152612525-61cdeaf3-7506-4cfe-b595-2829f93f4c22.png)

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/011522163849b5029218b7df95060f46d8f5ab6a
