### ISSUE TITLE
os.path.join

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_scratches#4]
path = app_path(APP_DIR_PY) + '/cuda_scratches/scratches/'
->
PATH = os.path.join( app_path(APP_DIR_DATA), 'scratches')

it handles OS separator (windows or unix) good.

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/0a9985d78f7f74e57fac77fbfb2d73c4ff985843

**Comment by Alexey-T** [comment]
PATH = os.path.join(app_path(APP_DIR_DATA), 'scratches') +os.sep

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/16565ac28c6a0e8f8513be6beda0bf4fc7611f55
