### ISSUE TITLE
suggested text for readme.txt

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_scratches#6]
Plugin gives few commands in the menu "Plugins / Scratches":

- "New" - Create a new snippet (scratch), with the lexer which you choose in the menu-dialog.
- "List" - Show menu-dialog with available snippets  (scratches), which you already created before.
- "Remove" - Delete some available snippet (scratch), which you created before.

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/dcb1bca34e7f20bda9d21ff61268042db5e5c4dd
